config/routes.rb
Rails.application.routes.draw do
  get 'city/edit'

  get 'city/create'

  get 'city/update'

  get 'city/destroy'

  resources :gyms
  resources :physical_people
  resources :addresses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/physical_people_controller.rb
class PhysicalPeopleController < ApplicationController
  before_action :set_physical_person, only: [:show, :edit, :update, :destroy]

  # GET /physical_people
  # GET /physical_people.json
  def index
    @physical_people = PhysicalPerson.all
  end

  # GET /physical_people/1
  # GET /physical_people/1.json
  def show
  end

  # GET /physical_people/new
  def new
    @physical_person = PhysicalPerson.new
  end

  # GET /physical_people/1/edit
  def edit
  end

  # POST /physical_people
  # POST /physical_people.json
  def create
    @physical_person = PhysicalPerson.new(physical_person_params)

    respond_to do |format|
      if @physical_person.save
        format.html { redirect_to @physical_person, notice: 'Physical person was successfully created.' }
        format.json { render :show, status: :created, location: @physical_person }
      else
        format.html { render :new }
        format.json { render json: @physical_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physical_people/1
  # PATCH/PUT /physical_people/1.json
  def update
    respond_to do |format|
      if @physical_person.update(physical_person_params)
        format.html { redirect_to @physical_person, notice: 'Physical person was successfully updated.' }
        format.json { render :show, status: :ok, location: @physical_person }
      else
        format.html { render :edit }
        format.json { render json: @physical_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physical_people/1
  # DELETE /physical_people/1.json
  def destroy
    @physical_person.destroy
    respond_to do |format|
      format.html { redirect_to physical_people_url, notice: 'Physical person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physical_person
      @physical_person = PhysicalPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physical_person_params
      params.require(:physical_person).permit(:cnpj, :nome_fantasia, :person_id)
    end
end

app/helpers/physical_people_helper.rb
module PhysicalPeopleHelper
end

app/views/physical_people/_form.html.erb
<%= form_for(physical_person) do |f| %>
  <% if physical_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(physical_person.errors.count, "error") %> prohibited this physical_person from being saved:</h2>

      <ul>
      <% physical_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>

  <div class="field">
    <%= f.label :nome_fantasia %>
    <%= f.text_field :nome_fantasia %>
  </div>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.text_field :person_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physical_people/edit.html.erb
<h1>Editing Physical Person</h1>

<%= render 'form', physical_person: @physical_person %>

<%= link_to 'Show', @physical_person %> |
<%= link_to 'Back', physical_people_path %>

app/views/physical_people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Physical People</h1>

<table>
  <thead>
    <tr>
      <th>Cnpj</th>
      <th>Nome fantasia</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physical_people.each do |physical_person| %>
      <tr>
        <td><%= physical_person.cnpj %></td>
        <td><%= physical_person.nome_fantasia %></td>
        <td><%= physical_person.person %></td>
        <td><%= link_to 'Show', physical_person %></td>
        <td><%= link_to 'Edit', edit_physical_person_path(physical_person) %></td>
        <td><%= link_to 'Destroy', physical_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physical Person', new_physical_person_path %>

app/views/physical_people/new.html.erb
<h1>New Physical Person</h1>

<%= render 'form', physical_person: @physical_person %>

<%= link_to 'Back', physical_people_path %>

app/views/physical_people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnpj:</strong>
  <%= @physical_person.cnpj %>
</p>

<p>
  <strong>Nome fantasia:</strong>
  <%= @physical_person.nome_fantasia %>
</p>

<p>
  <strong>Person:</strong>
  <%= @physical_person.person %>
</p>

<%= link_to 'Edit', edit_physical_person_path(@physical_person) %> |
<%= link_to 'Back', physical_people_path %>