config/routes.rb
Rails.application.routes.draw do
  get 'city/edit'

  get 'city/create'

  get 'city/update'

  get 'city/destroy'

  resources :gyms
  resources :physical_people
  resources :addresses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:rua, :numero, :complemento, :bairro, :cep, :city_id, :person_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rua %>
    <%= f.text_field :rua %>
  </div>

  <div class="field">
    <%= f.label :numero %>
    <%= f.text_field :numero %>
  </div>

  <div class="field">
    <%= f.label :complemento %>
    <%= f.text_field :complemento %>
  </div>

  <div class="field">
    <%= f.label :bairro %>
    <%= f.text_field :bairro %>
  </div>

  <div class="field">
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>

  <div class="field">
    <%= f.label :city_id %>
    <%= f.text_field :city_id %>
  </div>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.text_field :person_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Rua</th>
      <th>Numero</th>
      <th>Complemento</th>
      <th>Bairro</th>
      <th>Cep</th>
      <th>City</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.rua %></td>
        <td><%= address.numero %></td>
        <td><%= address.complemento %></td>
        <td><%= address.bairro %></td>
        <td><%= address.cep %></td>
        <td><%= address.city %></td>
        <td><%= address.person %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rua:</strong>
  <%= @address.rua %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @address.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @address.complemento %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @address.bairro %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @address.cep %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Person:</strong>
  <%= @address.person %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>