config/routes.rb
Rails.application.routes.draw do
  get 'city/edit'

  get 'city/create'

  get 'city/update'

  get 'city/destroy'

  resources :gyms
  resources :physical_people
  resources :addresses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gym.rb
class Gym < ApplicationRecord
  belongs_to :physical_person, inverse_of: :gyms
  accepts_nested_attributes_for :physical_person, allow_destroy: :true
  validates :phisical_person, presence: true
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
    @physical_person = @gym.build_physical_person
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)
    respond_to do |format|
      if @gym.save
        format.html { redirect_to @gym, notice: 'Gym was successfully created.' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:filial, :physical_person_id,
                                  physical_person_attributes: [:cnpj, :nome_fantasia, :person_id,
                                                               person_attributes: [:nome, :telefone, :celular]])
    end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= form_for(gym) do |f| %>
  <% if gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= f.label :filial %>
      <%= f.number_field :filial %>
    </div>

    <div class="field">
      <%= f.hidden_field :physical_person_id %>
    </div>

       <%= f.fields_for :physical_person do |pp| %>
        <div class="field">
          <%= pp.label :cnpj %>
          <%= pp.text_field :cnpj %>
        </div>

        <div class="field">
          <%= pp.label :nome_fantasia %>
          <%= pp.text_field :nome_fantasia %>
        </div>

        <div class="field">
          <%= pp.hidden_field :person_id %>
        </div>

            <%= pp.fields_for :person do |p| %>
                <div class="field">
                  <%= p.label :nome %>
                  <%= p.text_field :nome %>
                </div>

                <div class="field">
                  <%= p.label :telefone %>
                  <%= p.text_field :telefone %>
                </div>

                <div class="field">
                  <%= p.label :celular %>
                  <%= p.text_field :celular %>
                </div>
            <% end %>

        <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/gyms/edit.html.erb
<h1>Editing Gym</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gyms_path %>

app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gyms</h1>

<table>
  <thead>
    <tr>
      <th>Filial</th>
      <th>Physical person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gyms.each do |gym| %>
      <tr>
        <td><%= gym.filial %></td>
        <td><%= gym.physical_person %></td>
        <td><%= link_to 'Show', gym %></td>
        <td><%= link_to 'Edit', edit_gym_path(gym) %></td>
        <td><%= link_to 'Destroy', gym, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gym', new_gym_path %>

app/views/gyms/new.html.erb
<h1>New Gym</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Back', gyms_path %>

app/views/gyms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filial:</strong>
  <%= @gym.filial %>
</p>

<p>
  <strong>Physical person:</strong>
  <%= @gym.physical_person %>
</p>

<%= link_to 'Edit', edit_gym_path(@gym) %> |
<%= link_to 'Back', gyms_path %>